language: python
python:
- "2.7"
branches:
  only:
    - docker_swarm_centos
    
before_install:
  - sudo apt-get update -qq

install:
  - pip install -r tests/test-requirements.txt
script:
  - ansible-lint playbooks/*.yml -x 303,701,601,206,602,403,301,502,306

