- name: Create VMs
  hosts:  local
  gather_facts: no
  connection: local
  vars:
      gcp_project: "{{ lookup('env','GCP_PROJECT') }}"
      gcp_cred_kind: "{{ lookup('env','GCP_AUTH_KIND') }}"
      gcp_cred_file: "{{ lookup('env','GCP_SERVICE_ACCOUNT_FILE') }}"
      zone: "{{ lookup('env','GCP_ZONE') }}"
      region: "{{ lookup('env','GCP_REGION') }}"
      scope: "{{ lookup('env','GCP_SCOPES') }}"
  tasks:
 # - name: create a network
 #   gcp_compute_network:
 #    name: ansible-network
 #     auto_create_subnetworks: yes
 #     project: "{{ gcp_project }}"
 #     auth_kind: "{{ gcp_cred_kind }}"
 #     service_account_file: "{{ gcp_cred_file }}"
 #     state: present
 #     scopes:
 #       - "{{ scope }}"
 #   register: network

  - name: create a disk
    gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/centos-cloud/global/images/centos-7-v20200811
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#     service_account_file: "{{ gcp_cred_file }}"
      state: present
      scopes:
        - "{{ scope }}"
    register: disk
  
  - name: create a disk2
    gcp_compute_disk:
      name: disk-instance2
      size_gb: 50
      source_image: projects/centos-cloud/global/images/centos-7-v20200811
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
#      service_account_file: "{{ gcp_cred_file }}"
      state: present
      scopes:
        - "{{ scope }}"
    register: disk2

  - name: create a address
    gcp_compute_address:
      name: address-instance
      region: "{{ region }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
 #     service_account_file: "{{ gcp_cred_file }}"
      state: present
      scopes:
        - "{{ scope }}"
    register: address

  - name: Print address
    debug: 
      msg: "{{ address.address }}"

  - name: create a instance
    gcp_compute_instance:
      name: swarm-01
      machine_type: n1-standard-1  #or e2-small 
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      network_interfaces:
        - network: null
          access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
           - "{{ scope }}"
      tags:
        items:
          - manager
      state: present
        
  - name: Wait for SSH to come up
    wait_for: host={{ address.address }} port=22 delay=10 timeout=60
    
#  - name: Add host to groupname
#    add_host: hostname={{ address.address }} groupname=new_instances

    
  - name: create a address2
    gcp_compute_address:
      name: address-instance2
      region: "{{ region }}"    
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
 #     service_account_file: "{{ gcp_cred_file }}"
      state: present
      scopes:
        - "{{ scope }}"
    register: address2
    
  - name: create second instance
    gcp_compute_instance:
      name: swarm-02
      machine_type: n1-standard-1 #oppure e2-small
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk2 }}"
      network_interfaces:
        - access_configs:
          - name: External NAT
            nat_ip: "{{ address2 }}"
            type: ONE_TO_ONE_NAT
      zone: "{{ zone }}"
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      scopes:
           - "{{ scope }}"
      state: present

   

  - name: Wait for SSH to come up
    wait_for: host={{ address2.address }} port=22 delay=10 timeout=60
    
#  - name: Add host to groupname
#    add_host: hostname={{ address2.address }} groupname=new_instances


- name: "Configure VM - user creation"
  hosts: 
    - swarm-01
    - swarm-02
  become: yes
  roles:
    - { role: "nickjj.user", tags: "user" }


- name: "Provision Docker Swarm Cluster"
  hosts: 
    - swarm-01
    - swarm-02
  become: yes
  roles:
    - { role: atosatto.docker-swarm }
    
- name: Install Swarmpit UI
  hosts:  swarm-01
  gather_facts: no
  tasks:   
  - name: install swamrpit
    command: docker run -it --rm --name swarmpit-installer  -e INTERACTIVE=0 -e ADMIN_USERNAME=admin - e STACK_NAME=swarmui -e APP_PORT=888 -e ADMIN_PASSWORD=administrator --volume /var/run/docker.sock:/var/run/docker.sock swarmpit/install:1.9
  register: swarmpitui

- name: Open GCP Firewall ports
  hosts:  local
  gather_facts: no
  connection: local
  vars:
      gcp_project: "{{ lookup('env','GCP_PROJECT') }}"
      gcp_cred_kind: "{{ lookup('env','GCP_AUTH_KIND') }}"
      scope: "{{ lookup('env','GCP_SCOPES') }}"
  tasks:
  - name: create a firewall rule for UI
    gcp_compute_firewall:
      name: ui-swarmpit55
      allowed:
        -  ip_protocol: tcp
           ports: '8080'
      auth_kind: "{{ gcp_cred_kind }}"
      project: "{{ gcp_project }}"
      direction: "INGRESS"
      target_tags: 
        - manager
      scopes:
        - "{{ scope }}"
      state: present
  - name: create a firewall rule for NGINX
    gcp_compute_firewall:
      name: ui-nginx55
      allowed:
        -  ip_protocol: tcp
           ports: 
             - '888'
      auth_kind: "{{ gcp_cred_kind }}"
      project: "{{ gcp_project }}"
      direction: "INGRESS"
      target_tags: 
        - manager
      scopes:
        - "{{ scope }}"
      state: present